version: '3'

services:
  mysql:
    image: mysql:8
    volumes:
      - ./mysql_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: ecommerce_db
    networks:
      - net
  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin:5
    restart: always
    ports:
      - '8080:80'
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: password
    networks:
      - net
  php:
    depends_on:
      - mysql
    build:
      context: .
      dockerfile: ./php.dockerfile
    restart: always
    volumes:
      - ./:/var/www/html
    # command: bash -c "chmod -R 777 /var/www/html/media && docker-php-entrypoint php-fpm"
    networks:
      - net
  nginx:
    depends_on:
      - php
    image: nginx:1
    restart: always
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - net
networks:
  net: